name: Test
on:
  - pull_request
  - workflow_dispatch
  - merge_group

jobs:
  unit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - name: Unit Tests
        run: pnpm test:unit

  integration:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - name: Integration Tests
        run: pnpm test:int
